### ISSUE TITLE
Push containers to docker hub

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap-docker#11]
When we change this repository, a new container should be pushed to docker hub.

**Comment by marcin-krolik** [comment]
Some plugins require additional tools installed like `util-linux`, `sysstats` etc. In order to execute large tests plugin author will need to prepare docker images with all required tools installed. Do you plan to store such Dockerfiles in this repo as well? If so, how it will be structured? Separate folder per plugin? 

Additionally I suggest to include Alpine based docker image with Python and `spytest` module added. For large test to `psutil`, `meminfo` and `load` I used below Dockerfile andI'm storing image on my public docker hub.

```Dockerfile
FROM python:2.7.12-alpine

RUN apk update && \\
        apk add bash && \\
        rm -rf /var/cache/apk/* && \\
        pip install spytest
```

**Comment by nanliu** [comment]
@marcin-krolik, please submit any changes you like to see to the alpine_test/dockerfile. We have docker push enabled now whenever we change the containers.
